/*
 * API Farkle
 * API pour gérer un jeu de farkle.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * RestDices
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-04-17T15:57:35.862309694Z[GMT]")

public class RestDices {
  @SerializedName("dices")
  private List<Integer> dices = null;

  @SerializedName("score")
  private Integer score = null;

  public RestDices dices(List<Integer> dices) {
    this.dices = dices;
    return this;
  }

  public RestDices addDicesItem(Integer dicesItem) {
    if (this.dices == null) {
      this.dices = new ArrayList<Integer>();
    }
    this.dices.add(dicesItem);
    return this;
  }

   /**
   * Get dices
   * @return dices
  **/
  @Schema(description = "")
  public List<Integer> getDices() {
    return dices;
  }

  public void setDices(List<Integer> dices) {
    this.dices = dices;
  }

  public RestDices score(Integer score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @Schema(description = "")
  public Integer getScore() {
    return score;
  }

  public void setScore(Integer score) {
    this.score = score;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestDices restDices = (RestDices) o;
    return Objects.equals(this.dices, restDices.dices) &&
        Objects.equals(this.score, restDices.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dices, score);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestDices {\n");
    
    sb.append("    dices: ").append(toIndentedString(dices)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
